replicaCount: 1

image:
  repository: registry
  tag: 2.8.1
  pullPolicy: IfNotPresent

env:
  RegistryAuth:
    name: REGISTRY_AUTH
    value: htpasswd
  RegistryAuthRealm:
    name: REGISTRY_AUTH_HTPASSWD_REALM
    value: Registry Realm
  RegistryAuthPath:
    name: REGISTRY_AUTH_HTPASSWD_PATH
    value: /auth/htpasswd

registryContainerPort: 5000
registryServicePort: 5000

registryResources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 250Mi

secrets:
  registryAuthName: registry-auth
  registryConfigName: registry-docker-config
  defaultUsername: root
  defaultPassword: ""  # must be set on installation

volume:
  pvcName: velocity-registry-pvc
  storage: 10Gi
  storageClass: ebs-sc

url:
  prefix: registry-velocity
  domain: "" # must be set on installation