{{- if and (.Values.aws.creds.accessKey) (.Values.aws.creds.secretKey) (.Values.aws.region) }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-developer
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: {{ .Values.aws.creds.accessKey }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.aws.creds.secretKey }}
    AWS_SESSION_TOKEN: ""
{{- end }}
