{{- if and (.Values.aws.creds.accessKey) (.Values.aws.creds.secretKey) (.Values.aws.region) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aws.creds.k8sSecretName}}
type: Opaque
stringData:
  credentials: |
    [default]
    region = {{ .Values.aws.region}}
    aws_access_key_id = {{ .Values.aws.creds.accessKey }}
    aws_secret_access_key = {{ .Values.aws.creds.secretKey }}
{{- end }}