apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-manager
  labels:
  {{- include "chart.labels" . | nindent 4 }}
{{- if .Values.controllerManager.manager.saImagePullSecrets }}
imagePullSecrets:
{{- range .Values.controllerManager.manager.saImagePullSecrets }}
  - name: {{ . }}
{{- end}}
{{- end }}

