apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role{{ .Values.globalSuffix | default "" }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding{{ .Values.globalSuffix | default "" }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role{{ .Values.globalSuffix | default "" }}'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-manager'
  namespace: '{{ .Release.Namespace }}'
