apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "" # core api group
  - apps
  - extensions
  - networking.k8s.io/v1
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
{{- if .Values.tags.cloudResources2 }}
- apiGroups:
    - dynamodb.services.k8s.aws
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - s3.services.k8s.aws
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - sns.services.k8s.aws
  resources:
    - '*'
  verbs:
    - '*'
- apiGroups:
    - sqs.velocity.tech
  resources:
    - '*'
  verbs:
    - '*'
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-manager'
  namespace: '{{ .Release.Namespace }}'
