apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ required "a valid AWS region required" .Values.aws.region }}
  CLOUD_RESOURCES_ENABLED:  {{ quote .Values.tags.cloudResources }}
