apiVersion: v2
name: velocity-operator
description: |-
  Spin up fully isolated, ephemeral environments in seconds.
  Develop code on your local machine and test it on a production-like environment.
type: application
version: 0.1.0

dependencies:
  - name: s3-chart
    version: v0.1.5
    repository: "oci://public.ecr.aws/aws-controllers-k8s"
    condition: cloudResources.s3.enabled
    tags:
      - cloud-resources
  - name: dynamodb-chart
    version: v0.1.7
    repository: "oci://public.ecr.aws/aws-controllers-k8s"
    condition: cloudResources.dynamodb.enabled
    tags:
      - cloud-resources
  - name: sqs-controller-chart # Velocity inhouse chart
    repository: "oci://quay.io/velocity"
    version: 0.0.5
    condition: cloudResources.sqs.enabled
    tags:
      - cloud-resources
  - name: ack-sns-controller
    repository: "oci://quay.io/velocity" # We don't pull the official because https://github.com/aws-controllers-k8s/community/issues/1535
    version: v0.0.3
    condition: cloudResources.sns.enabled
    tags:
      - cloud-resources
