apiVersion: v2
name: velocity-operator
description: |-
  Spin up fully isolated, ephemeral environments in seconds.
  Develop code on your local machine and test it on a production-like environment.
type: application
version: 0.1.2
