apiVersion: v2
name: velocity-operator
description: |-
  Spin up fully isolated, ephemeral environments in seconds.
  Develop code on your local machine and test it on a production-like environment.
type: application
version: 0.2.32
appVersion: v1.6.1
# IMPORTANT: When upgrading the AWS ACK controller versions, make sure to update the `templates/crds` files
# according to the new version CRDs.
# The `fieldexports` and `adoptedresources` CRDs are defined under `templates/crds/aws`
# We duplicate the CRDs internally because helm does not install CRDs if running with `helm upgrade`
# Please see `README.md` for more details.
dependencies:
  - name: s3-chart
    version: v0.1.5
    repository: "https://helm-charts.velocity.tech"
    condition: cloudResources.s3.enabled
    tags:
      - cloudResources
  - name: dynamodb-chart
    version: v0.1.7
    repository: "https://helm-charts.velocity.tech"
    condition: cloudResources.dynamodb.enabled
    tags:
      - cloudResources
  - name: sqs-controller-chart
    # Velocity inhouse chart
    repository: "https://helm-charts.velocity.tech"
    version: 0.0.6
    condition: cloudResources.sqs.enabled
    tags:
      - cloudResources
  - name: ack-sns-controller
    # We don't pull the official because https://github.com/aws-controllers-k8s/community/issues/1535
    repository: "https://helm-charts.velocity.tech"
    version: v0.0.3
    condition: cloudResources.sns.enabled
    tags:
      - cloudResources
