controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    env:
      dryRun: false
    saImagePullSecrets: []
    image:
      repository: quay.io/velocity/velocity-operator
#     tag: v0.0.7 use appVersion by default
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: 10510bd1.velocity.tech
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
secrets:
  authToken: replace-me

aws:
  region:
  creds:
    accessKey:
    secretKey:

    k8sSecretName: aws-creds
    k8sSecretKeyName: credentials
    profile: default

velocity:
  apiUrl: ""

tags:
  cloudResources: false   # All cloud resources will be enabled if this is true

s3-chart:
  aws:
    region: us-east-1 # default value. for environment creation, we use a namespace annotation to indicate the region
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default

dynamodb-chart:
  aws:
    region: us-east-1 # default value. for environment creation, we use a namespace annotation to indicate the region
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default


sqs-controller-chart:
  aws:
    region: us-east-1 # default value. for environment creation, we use a namespace annotation to indicate the region
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default

ack-sns-controller:
  aws:
    region: us-east-1 # default value. for environment creation, we use a namespace annotation to indicate the region
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default
