controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    image:
      repository: gcr.io/techvelocity-dev/velocity-operator
      tag: v0.0.1
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: 10510bd1.velocity.tech
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
secrets:
  authToken: replace-me

aws:
  region: &aws-region us-east-1
  creds:
    accessKey:
    secretKey:

    k8sSecretName: &k8s-secret-name aws-creds
    k8sSecretKeyName: &k8s-secret-key-name credentials
    profile: &aws-profile default

tags:
  cloud-resources: false # All cloud resources will be enabled if this is true

s3-chart:
  aws:
    region: *aws-region
    credentials:
      secretName: *k8s-secret-name
      secretKey: *k8s-secret-key-name
      profile: *aws-profile

dynamodb-chart:
  aws:
    region: *aws-region
    credentials:
      secretName: *k8s-secret-name
      secretKey: *k8s-secret-key-name
      profile: *aws-profile


sqs-controller-chart:
  fullnameOverride: sqs
  aws:
    region: *aws-region
    credentials:
      secretName: *k8s-secret-name
      secretKey: *k8s-secret-key-name
      profile: *aws-profile

ack-sns-controller:
  aws:
    region: *aws-region
    credentials:
      secretName: *k8s-secret-name
      secretKey: *k8s-secret-key-name
      profile: *aws-profile
