controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  manager:
    env:
    # NAME: value
    saImagePullSecrets: []
    image:
      repository: quay.io/velocity/velocity-operator
      # tag: v0.0.7 use appVersion by default
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1

rbac:
  allowAll: true

managerConfig:
  controllerManagerConfigYaml:
    health:
      healthProbeBindAddress: :8081
    leaderElection:
      leaderElect: true
      resourceName: 10510bd1.velocity.tech
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443

metricsService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  type: ClusterIP
secrets:
  authToken: replace-me

aws:
  # default value. for environment creation, we use a namespace annotation to determine the region
  region: us-east-1
  creds:
    accessKey:
    secretKey:

    k8sSecretName: aws-creds
    k8sSecretKeyName: credentials
    profile: default

tags:
  # All cloud resources will be enabled if this is true
  cloudResources: false

s3-chart:
  aws:
    # default value. for environment creation, we use a namespace annotation to determine the region
    region: us-east-1
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default

dynamodb-chart:
  aws:
    # default value. for environment creation, we use a namespace annotation to determine the region
    region: us-east-1
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default

sqs-chart:
  aws:
    # default value. for environment creation, we use a namespace annotation to determine the region
    region: us-east-1
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default

ack-sns-controller:
  aws:
    # default value. for environment creation, we use a namespace annotation to determine the region
    region: us-east-1
    credentials:
      secretName: aws-creds
      secretKey: credentials
      profile: default
