apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-manager-secret
  labels:
  {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  authToken: {{ .Values.secrets.authToken | toString | b64enc }}
