{{- if .Values.operator.admissionWebhook.autoSelfSignedCertificate -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-cert
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: operator
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data: {{- include "operator.webhook.certificate.self-signed.generated-cert" . | nindent 2 -}}
{{- end -}}