apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildkit.name" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "buildkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.rootless .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.rootless }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: unconfined
        {{- end }}
        {{- with .Values.podAnnotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        app: {{ include "buildkit.name" . }}
        {{- include "buildkit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "buildkit.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{- if or .Values.rootless .Values.tls.enabled }}
          {{- if .Values.tls.enabled }}
          - name: certs
            readOnly: true
            mountPath: /certs
          {{- end }}
          {{- if .Values.rootless }}
          - mountPath: /home/user/.local/share/buildkit
            name: buildkitd
          {{- end }}
          {{- end }}
          - mountPath: /etc/buildkit
            name: config
          - mountPath: /var/lib/buildkit
            name: var-lib-buildkit
          args:
            - --addr
            - unix:///run/{{ .Values.rootless | ternary "user/1000" ""}}/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
          {{- if .Values.rootless }}
          - --oci-worker-no-process-sandbox
          {{- end }}
          {{- if .Values.tls.enabled }}
          - --tlscacert
          - /certs/ca.pem
          - --tlscert
          - /certs/cert.pem
          - --tlskey
          - /certs/key.pem
          {{- end }}
          ports:
            - name: tcp
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            {{- if .Values.rootless }}
            seccompProfile: # Needs Kubernetes >= 1.19
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
            {{- else }}
            privileged: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - configMap:
          name: {{ include "buildkit.name" . }}
        name: config
      - name: var-lib-buildkit
        persistentVolumeClaim:
          claimName: {{ include "buildkit.name" . }}
      {{- if or .Values.rootless .Values.tls.enabled }}
      {{- if .Values.rootless }}
      - name: buildkitd
        emptyDir: {}
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: certs
        secret:
          secretName: {{ include "buildkit.name" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
