{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildkit.name" . }}
data:
  ca.pem: {{ include "buildkit.tlsCertCACert" . }}
  cert.pem: {{ include "buildkit.tlsCert" . }}
  key.pem: {{ include "buildkit.tlsCertKey" . }}
{{- end }}
