apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
spec:
  ports:
  - name: {{ .Values.registryServicePort }}-tcp
    port: {{ .Values.registryServicePort }}
    protocol: TCP
    targetPort: {{ .Values.registryContainerPort }}
