apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}