apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" (include "utils.urlAuthBuilder" . ) (include "utils.credendtialsAuthBuild" . ) | b64enc }}
metadata:
  name: {{ .Values.secrets.registryConfigName }}
type: kubernetes.io/dockerconfigjson
