apiVersion: v1
kind: Secret
data:
  htpasswd: {{ (htpasswd .Values.secrets.defaultUsername .Values.secrets.defaultPassword) | b64enc  }}
metadata:
  name: {{ .Values.secrets.registryAuthName }}
type: Opaque
