apiVersion: v1
appVersion: v0.1.7
description: A Helm chart for the ACK service controller for Amazon DynamoDB (DynamoDB)
home: https://github.com/aws-controllers-k8s/dynamodb-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
keywords:
- aws
- kubernetes
- dynamodb
maintainers:
- name: ACK Admins
  url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
- name: DynamoDB Admins
  url: https://github.com/orgs/aws-controllers-k8s/teams/dynamodb-maintainer
name: dynamodb-chart
sources:
- https://github.com/aws-controllers-k8s/dynamodb-controller
version: v0.1.7
