name: Release Charts

on:  
  push:
    branches:
      - main
      - fix/VELO-72-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "techvelocity-ci"
          git config user.email "techvelocity+ci@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.15.2

      - name: Helm Deps
        run: |
          helm repo add charts https://helm-charts.velocity.tech

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          pages_branch: gh-pages-v2
        env:
          CR_TOKEN: "${{ secrets.TECHVELOCITY_CI_GITHUB_TOKEN_HELM_CHARTS }}"
